server:
  port: 8082

spring:
  application:
    name: feign-server

eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka

feign:
  httpclient:
    disable-ssl-validation: true

  okhttp:
    enabled: true